/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImportLocalBook.java
 *
 * Created on 2010-12-12, 16:37:10
 */
package booksystem;

import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFrame;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.*;
import javax.swing.JOptionPane;

import BackGround.BookItem;
import BackGround.HandleXML;
import BackGround.FormChangedObservable;
import java.util.List;

//使用观察者模式来设计
//import java.util.Observable;
import java.util.Observer;
/**
 *
 * @author Administrator
 */
public class ImportLocalBook extends javax.swing.JFrame{
    
    private BookItem bookItem;
    private HandleXML xmlHander;
    private FormChangedObservable observable;
    private static Observer observer;
    /** Creates new form ImportLocalBook */
    public ImportLocalBook(Observer observer) {
        initComponents();
        bookItem = new BookItem();
        observable = new FormChangedObservable();
        this.observer = observer;
        observable.addObserver(observer);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookName = new javax.swing.JLabel();
        bookISBN = new javax.swing.JLabel();
        bookBranch = new javax.swing.JLabel();
        bookLocation = new javax.swing.JLabel();
        jTextFieldBookName = new javax.swing.JTextField();
        jTextFieldBookISBN = new javax.swing.JTextField();
        jTextFieldBookLocation = new javax.swing.JTextField();
        jButtonChooseBook = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        bookAuthor = new javax.swing.JLabel();
        jTextFieldBookAuthor = new javax.swing.JTextField();
        jComboBoxBookBranch = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBookDescription = new javax.swing.JTextArea();
        bookDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("选择本地书籍");
        setBackground(new java.awt.Color(240, 240, 255));

        bookName.setText("书籍名称");

        bookISBN.setText("ISBN");

        bookBranch.setText("书籍分类");

        bookLocation.setText("书籍本地地址");

        jButtonChooseBook.setText("浏览");
        jButtonChooseBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChooseBookMouseClicked(evt);
            }
        });

        jButtonOK.setText("确定");
        jButtonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKMouseClicked(evt);
            }
        });
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("取消");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        bookAuthor.setText("作者");

        jComboBoxBookBranch.setEditable(true);
        jComboBoxBookBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "科学", "杂志", "小说", "计算机" }));

        jTextAreaBookDescription.setColumns(20);
        jTextAreaBookDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaBookDescription);

        bookDescription.setText("书籍简介");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookName)
                            .addComponent(bookISBN)
                            .addComponent(bookLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookBranch)
                            .addComponent(bookAuthor))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bookDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxBookBranch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBookAuthor)
                    .addComponent(jTextFieldBookLocation)
                    .addComponent(jTextFieldBookISBN)
                    .addComponent(jTextFieldBookName, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChooseBook)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookName)
                    .addComponent(jTextFieldBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookISBN)
                    .addComponent(jTextFieldBookISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookAuthor)
                    .addComponent(jTextFieldBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookBranch)
                    .addComponent(jComboBoxBookBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookLocation)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBookLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonChooseBook)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOK)
                            .addComponent(jButtonCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(bookDescription)))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChooseBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChooseBookMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = 
                new FileNameExtensionFilter("支持文件类型（*.txt，*.pdf，*.doc，*.chm，*.jpg，*.gif，*.bmp）",
                "pdf", "doc", "chm", "jpg", "gif", "bmp");
        //chooser.setFileFilter(filter);
        chooser.addChoosableFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            jTextFieldBookLocation.setText(selectedFile.getPath());
        }

    }//GEN-LAST:event_jButtonChooseBookMouseClicked

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKMouseClicked
        // TODO add your handling code here:
        if ( jTextFieldBookName.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Attention: Please input the Bookname!");
            resetDialog();
        }
        else if(jTextFieldBookLocation.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Attention: Please input or select the Book path!");
            //resetDialog();
            jTextFieldBookName.setText(null);
        }
        else if(isFilePathValid(jTextFieldBookLocation.getText()) != true)
        {
            JOptionPane.showMessageDialog(this, "Sorry, this book does NOT exist!");
            //resetDialog();
            jTextFieldBookLocation.setText(null);
        }
        else
        {
            xmlHander = new HandleXML();
            String lastID = xmlHander.getTheLastBookItemID();
            Integer toIntID = Integer.parseInt(lastID);
            toIntID++;
            String newID = toIntID.toString();
            createBookItem();
            bookItem.setId(newID);
            xmlHander.addNewNode(bookItem);
            this.setVisible(false);
            
            //通知调用者，表格已经提交
            observable.setChanged();
            observable.notifyObservers();
        }

    }//GEN-LAST:event_jButtonOKMouseClicked

    private void resetDialog() {
        jTextFieldBookName.setText(null);
        jTextFieldBookISBN.setText(null);
        jTextFieldBookAuthor.setText(null);
        jComboBoxBookBranch.setSelectedIndex(-1);
        jTextFieldBookLocation.setText(null);
        jTextAreaBookDescription.setText(null);
    }

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private boolean isFilePathValid(String path)
    {
        File file = new File(path);
        return file.exists();
    }

    private void createBookItem()
    {
        bookItem.setBookName(jTextFieldBookName.getText());
        bookItem.setBookISBN(jTextFieldBookISBN.getText());
        bookItem.setAuthor(jTextFieldBookAuthor.getText());
        bookItem.setBranch(jComboBoxBookBranch.getSelectedItem().toString());
        bookItem.setLocation(jTextFieldBookLocation.getText());
        bookItem.setDescription(jTextAreaBookDescription.getText());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportLocalBook(observer).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookAuthor;
    private javax.swing.JLabel bookBranch;
    private javax.swing.JLabel bookDescription;
    private javax.swing.JLabel bookISBN;
    private javax.swing.JLabel bookLocation;
    private javax.swing.JLabel bookName;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonChooseBook;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxBookBranch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaBookDescription;
    private javax.swing.JTextField jTextFieldBookAuthor;
    private javax.swing.JTextField jTextFieldBookISBN;
    private javax.swing.JTextField jTextFieldBookLocation;
    private javax.swing.JTextField jTextFieldBookName;
    // End of variables declaration//GEN-END:variables
}
