/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2010-12-12, 14:03:14
 */

package booksystem;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import BackGround.BookItem;
import BackGround.HandleXML;
import BackGround.BookTableModel;
import BackGround.ClassGlobal;
import BackGround.DatabaseConnector;
import BackGround.FriendTableModel;
import BackGround.User;
import java.awt.Image;
import javax.swing.table.TableModel;
import java.util.*;
import javax.swing.text.html.ImageView;
/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame implements Observer{

    private BookTableModel bookTableModelOfLocal;
    private BookTableModel bookTableModelOfServer;
    private FriendTableModel friendTable;
    private List<BookItem> bookListOfLocal;
    private List<BookItem> bookListOfServer;
    private List<User> friendList;
    private HandleXML xmlHander;
    /** Creates new form MainFrame */
    public MainFrame() {
       
        xmlHander = new HandleXML();
        bookListOfLocal = xmlHander.readLocalList("", "");
        bookTableModelOfLocal = new BookTableModel();
        bookTableModelOfLocal.setBookList(bookListOfLocal);
        friendTable = new FriendTableModel();
        //------------获取服务器上书籍列表-----------------
        DatabaseConnector databaseConnector = DatabaseConnector.getDatabaseConnectorInstance();
        databaseConnector.connect();
        bookListOfServer = databaseConnector.searchBook("bname", "");
        bookTableModelOfServer = new BookTableModel();
        bookTableModelOfServer.setBookList(bookListOfServer);
        //--------------------------------------------------

        //Image img = myFrame.getToolkit().createImage("xx.gif");
       // this.setIconImage("5.jpg");
        initComponents();
        jTableBooks.updateUI();
        databaseConnector.close();
    }

    //使用观察者模式
    public void update(Observable o, Object arg)
    {
        updateBookTable();
    }

    private void updateBookTable()
    {
        bookListOfLocal = xmlHander.readLocalList("", "");
        bookTableModelOfLocal.setBookList(bookListOfLocal);
        jTableBooks.updateUI();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonImportToLocalList = new javax.swing.JButton();
        jButtonDeleteFromLocalList = new javax.swing.JButton();
        jButtonAddBranch = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabelBranch = new javax.swing.JLabel();
        jComboBoxBranch = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFriends = new javax.swing.JTable();
        jLabelImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemImportBook = new javax.swing.JMenuItem();
        jMenuItemOpenBook = new javax.swing.JMenuItem();
        jMenuItemCreateBranch = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSaveLocalList = new javax.swing.JMenuItem();
        jMenuItemLoadLocalList = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuUser = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("E-Book-Classify-System");
        setForeground(java.awt.Color.gray);

        jButtonImportToLocalList.setText("导入书籍记录");
        jButtonImportToLocalList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonImportToLocalListMouseClicked(evt);
            }
        });

        jButtonDeleteFromLocalList.setText("删除书籍记录");
        jButtonDeleteFromLocalList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteFromLocalListMouseClicked(evt);
            }
        });

        jButtonAddBranch.setText("添加书籍分类");

        jButtonUpdate.setText("显示好友列表");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });

        jLabelBranch.setFont(new java.awt.Font("微软雅黑", 1, 12));
        jLabelBranch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBranch.setText("书籍分类");
        jLabelBranch.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxBranch.setEditable(true);
        jComboBoxBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "科学", "杂志", "小说", "计算机" }));

        jTableBooks.setModel(bookTableModelOfLocal);
        jScrollPane1.setViewportView(jTableBooks);

        jSeparator3.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(bookTableModelOfServer);
        jScrollPane2.setViewportView(jTable1);

        jSeparator4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableFriends.setModel(friendTable);
        jScrollPane3.setViewportView(jTableFriends);

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/05.jpg"))); // NOI18N
        jLabelImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 14));
        jLabel1.setText("本地图书列表");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 14));
        jLabel2.setText("EBCS免费在线书籍");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 14));
        jLabel3.setText("我的好友");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenuBar1.setBackground(new java.awt.Color(51, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(255, 102, 102));

        jMenuFile.setText("文件");

        jMenuItemImportBook.setText("添加本地书籍");
        jMenuItemImportBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemImportBookMousePressed(evt);
            }
        });
        jMenuFile.add(jMenuItemImportBook);

        jMenuItemOpenBook.setText("打开本地书籍");
        jMenuItemOpenBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemOpenBookMouseClicked(evt);
            }
        });
        jMenuFile.add(jMenuItemOpenBook);

        jMenuItemCreateBranch.setText("添加新分类");
        jMenuFile.add(jMenuItemCreateBranch);
        jMenuFile.add(jSeparator1);
        jMenuFile.add(jMenuItemSaveLocalList);

        jMenuItemLoadLocalList.setText("载入图书列表文件");
        jMenuFile.add(jMenuItemLoadLocalList);
        jMenuFile.add(jSeparator2);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setText("退出EBCS");
        jMenuItemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemExitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemExitMousePressed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("编辑");
        jMenuBar1.add(jMenuEdit);

        jMenuUser.setText("用户账户");

        jMenuItem1.setText("登录");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenuUser.add(jMenuItem1);

        jMenuItem2.setText("注册");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenuUser.add(jMenuItem2);

        jMenuItem3.setText("用户信息中心");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenuUser.add(jMenuItem3);

        jMenuBar1.add(jMenuUser);

        jMenuHelp.setText("帮助");

        jMenuItemAboutUs.setText("关于我们");
        jMenuItemAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemAboutUsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemAboutUsMousePressed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAboutUs);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonAddBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonImportToLocalList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteFromLocalList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxBranch, 0, 109, Short.MAX_VALUE)
                                .addGap(91, 91, 91))
                            .addComponent(jLabelImage)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2)))
                .addGap(24, 24, 24)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonImportToLocalList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteFromLocalList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddBranch))
                    .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBranch)
                    .addComponent(jComboBoxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogInMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuLogInMouseClicked

    private void jMenuItemAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAboutUsMouseClicked
        // TODO add your handling code here:
        //String about = "Team: Muse-Master"+"\n"+"Members:陈晓宇 胡程远 李志勋 吴凯发 杨光 曾仲";
        String about = "Team: Muse-Master";
        ShowMsg msg = new ShowMsg();
        msg.getPerblem(about);
        msg.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutUsMouseClicked

    private void jMenuItemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemExitMouseClicked

    private void jMenuItemOpenBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemOpenBookMouseClicked
        // TODO add your handling code here:
        FileChooser fc = new FileChooser();
        fc.setLocationRelativeTo(this);
        fc.setVisible(true);
    }//GEN-LAST:event_jMenuItemOpenBookMouseClicked

    private void jMenuItemAboutUsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAboutUsMousePressed
        // TODO add your handling code here:

        ClassGlobal cg = ClassGlobal.getInstance();
        cg.messageToShow = "小组名称Muse-Master";
        ShowMsg msg = new ShowMsg();
        msg.setLocationRelativeTo(this);
        msg.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutUsMousePressed

    private void jMenuItemExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemExitMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemExitMousePressed

    private void jMenuItemOpenBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemOpenBookMousePressed
        // TODO add your handling code here:
        FileChooser fc = new FileChooser();
        fc.setVisible(true);
    }//GEN-LAST:event_jMenuItemOpenBookMousePressed

    private void jButtonImportToLocalListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImportToLocalListMouseClicked
        // TODO add your handling code here:
        ImportLocalBook ilb = new ImportLocalBook(this);
        ilb.setLocationRelativeTo(this);
        ilb.setVisible(true);
    }//GEN-LAST:event_jButtonImportToLocalListMouseClicked

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        // TODO add your handling code here:
        ClassGlobal classGlobal = ClassGlobal.getInstance();
        if(classGlobal.loginState == true)
        {
            //------------获取服务器上朋友列表-----------------
            DatabaseConnector databaseConnector = DatabaseConnector.getDatabaseConnectorInstance();
            databaseConnector.connect();
            friendList = databaseConnector.getFriendList(classGlobal.GlobalUser.getName());
            friendTable.setFriendList(friendList);
            jTableFriends.updateUI();//悲剧了
            databaseConnector.close();
            //--------------------------------------------------
        }
        else
        {
            JOptionPane.showMessageDialog(this, "请先登录，才能看到好友列表");
        }
        //updateBookTable();
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonDeleteFromLocalListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteFromLocalListMouseClicked
        // TODO add your handling code here:
        if( jTableBooks.getSelectedRow() == -1 )//No book is selected
            JOptionPane.showMessageDialog(this, "Please choose the book you want to delete!");
        else
        {
            if( JOptionPane.YES_OPTION== showDeleteDialog())
            {
                //updateBookTable();
                int selectedRow = jTableBooks.getSelectedRow();
                String selectedBookID = bookListOfLocal.get(selectedRow).getId();
                xmlHander.deleteNode(selectedBookID);
                jTableBooks.clearSelection();
            }
        }
    }//GEN-LAST:event_jButtonDeleteFromLocalListMouseClicked

    private void jMenuItemImportBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemImportBookMousePressed
        // TODO add your handling code here:
        ImportLocalBook ilb = new ImportLocalBook(this);
        ilb.setLocationRelativeTo(this);
        ilb.setVisible(true);
    }//GEN-LAST:event_jMenuItemImportBookMousePressed

    private void jMenuLogInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogInMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuLogInMousePressed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        // TODO add your handling code here:
        ClassGlobal cg = ClassGlobal.getInstance();
        if(cg.loginState == true)
        {
            cg.messageToShow = "已成功登录！";
            ShowMsg smg = new ShowMsg();
            smg.setLocationRelativeTo(this);
            smg.setVisible(true);
        }
        else
        {
            UserLogin newLog = new UserLogin();
            newLog.setLocationRelativeTo(this);
            newLog.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        // TODO add your handling code here:
        Register r = new Register();
        r.setLocationRelativeTo(this);
        r.setVisible(true);
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        // TODO add your handling code here:
        ClassGlobal cg = ClassGlobal.getInstance();
        if(cg.loginState == true)
        {
            ChangeInfo changeInfo = new ChangeInfo();
            changeInfo.setLocationRelativeTo(this);
            changeInfo.setVisible(true);
        }
        else
        {
            cg.messageToShow = "尚未登录！请首先登陆！";
            ShowMsg smg = new ShowMsg();
            smg.setLocationRelativeTo(this);
            smg.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3MousePressed

    private int showDeleteDialog()
    {
        Object[] options = { "OK", "CANCEL" };
        int returnVal = JOptionPane.showOptionDialog(this, "Are you SURE to remove this book?", "Warning",
        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
        null, options, options[0]);
        return returnVal;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBranch;
    private javax.swing.JButton jButtonDeleteFromLocalList;
    private javax.swing.JButton jButtonImportToLocalList;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxBranch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBranch;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAboutUs;
    private javax.swing.JMenuItem jMenuItemCreateBranch;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemImportBook;
    private javax.swing.JMenuItem jMenuItemLoadLocalList;
    private javax.swing.JMenuItem jMenuItemOpenBook;
    private javax.swing.JMenuItem jMenuItemSaveLocalList;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JTable jTableFriends;
    // End of variables declaration//GEN-END:variables

}
