/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImportLocalBook.java
 *
 * Created on 2010-12-12, 16:37:10
 */
package booksystem;

import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFrame;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.*;
import javax.swing.JOptionPane;

import ForeGround.BookItem;
import ForeGround.HandleXML;
import java.util.List;
/**
 *
 * @author Administrator
 */
public class ImportLocalBook extends javax.swing.JFrame {
    
    private BookItem bookItem;
    private HandleXML xmlHander;

    /** Creates new form ImportLocalBook */
    public ImportLocalBook() {
        initComponents();
        bookItem = new BookItem();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookName = new javax.swing.JLabel();
        bookISBN = new javax.swing.JLabel();
        bookBranch = new javax.swing.JLabel();
        bookLocation = new javax.swing.JLabel();
        jTextFieldBookName = new javax.swing.JTextField();
        jTextFieldBookISBN = new javax.swing.JTextField();
        jTextFieldBookLocation = new javax.swing.JTextField();
        jButtonChooseBook = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        bookAuthor = new javax.swing.JLabel();
        jTextFieldBookAuthor = new javax.swing.JTextField();
        jComboBoxBookBranch = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bookName.setText("BookName");

        bookISBN.setText("BookISBN");

        bookBranch.setText("BookBranch");

        bookLocation.setText("BookLocation");

        jButtonChooseBook.setText("browser");
        jButtonChooseBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChooseBookMouseClicked(evt);
            }
        });

        jButtonOK.setText("OK");
        jButtonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKMouseClicked(evt);
            }
        });
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        bookAuthor.setText("BookAuthor");

        jComboBoxBookBranch.setEditable(true);
        jComboBoxBookBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookName)
                            .addComponent(bookISBN)
                            .addComponent(bookLocation)
                            .addComponent(bookBranch)
                            .addComponent(bookAuthor))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxBookBranch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldBookAuthor)
                            .addComponent(jTextFieldBookLocation)
                            .addComponent(jTextFieldBookISBN)
                            .addComponent(jTextFieldBookName, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChooseBook))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButtonOK)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonCancel)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookName)
                    .addComponent(jTextFieldBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookISBN)
                    .addComponent(jTextFieldBookISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookAuthor)
                    .addComponent(jTextFieldBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookBranch)
                    .addComponent(jComboBoxBookBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookLocation)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBookLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonChooseBook)))
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChooseBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChooseBookMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "pdf", "doc", "chm", "jpg", "gif", "bmp");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            jTextFieldBookLocation.setText(selectedFile.getPath());
        }

    }//GEN-LAST:event_jButtonChooseBookMouseClicked

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKMouseClicked
        // TODO add your handling code here:
        if ( jTextFieldBookName.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Attention: Please input the Bookname!");
            resetDialog();
        }
        else if(jTextFieldBookLocation.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Attention: Please input or select the Book path!");
            resetDialog();
        }
        else if(isFilePathValid(jTextFieldBookLocation.getText()) != true)
        {
            JOptionPane.showMessageDialog(this, "Sorry, this book does NOT exist!");
            resetDialog();
        }
        else
        {
            xmlHander = new HandleXML();
            String lastID = xmlHander.getTheLastBookItemID();
            Integer toIntID = Integer.parseInt(lastID);
            toIntID++;
            String newID = toIntID.toString();
            createBookItem();
            bookItem.setId(newID);
            xmlHander.addNewNode(bookItem);
            this.setVisible(false);
        }

    }//GEN-LAST:event_jButtonOKMouseClicked

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void resetDialog() {
        jTextFieldBookName.setText(null);
        jTextFieldBookISBN.setText(null);
        jComboBoxBookBranch.setSelectedIndex(-1);
        jTextFieldBookLocation.setText(null);
    }

    private boolean isFilePathValid(String path)
    {
        File file = new File(path);
        return file.exists();
    }

    private void createBookItem()
    {
        bookItem.setBookName(jTextFieldBookName.getText());
        bookItem.setBookISBN(jTextFieldBookISBN.getText());
        bookItem.setAuthor(jTextFieldBookAuthor.getText());
        bookItem.setLocation(jTextFieldBookLocation.getText());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ImportLocalBook().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookAuthor;
    private javax.swing.JLabel bookBranch;
    private javax.swing.JLabel bookISBN;
    private javax.swing.JLabel bookLocation;
    private javax.swing.JLabel bookName;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonChooseBook;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxBookBranch;
    private javax.swing.JTextField jTextFieldBookAuthor;
    private javax.swing.JTextField jTextFieldBookISBN;
    private javax.swing.JTextField jTextFieldBookLocation;
    private javax.swing.JTextField jTextFieldBookName;
    // End of variables declaration//GEN-END:variables
}
